on:
  pull_request:
    paths: [code/**, .github/workflows/Build.yaml]
  workflow_dispatch:
name: Build
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
defaults:
  run:
    shell: bash
    working-directory: code
jobs:
  build:
    name: "Build"
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6

      - name: "Update apt package list"
        run: |
          sudo apt-get update

      - name: "Install core system requirements"
        run: |
          sudo apt-get install -y --fix-missing libgmp-dev python3 graphviz g++ default-jdk mono-devel

      - name: "Update PATH"
        run: |
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: "Install Stack"
        uses: haskell-actions/setup@v2
        with:
          enable-stack: true
          stack-no-global: true
          stack-version: 'latest'

      - name: "Cache dependencies"
        uses: actions/cache@v5
        with:
          path: |
            ~/.stack
            ~/.cabal/packages
            ~/.cabal/store
            code/.stack-work/
            code/website/.stack-work/
            ~/.local/bin/graphmod
          key: ${{ runner.os }}-store-${{ hashFiles('code/stack.yaml') }}

      - name: "Clean previous run"
        run: make clean

      - name: "Install dependencies"
        run: make stackArgs="--no-terminal" deps

      - name: "Build"
        run: make code stackArgs="--no-terminal" GHCFLAGS="-Werror -Wwarn=deprecations"

      - name: "Install"
        run: stack install --local-bin-path=bin
      
      - uses: actions/upload-artifact@v7
        with:
          name: bin
          path: code/bin
  
  gen:
    name: Generate
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6

      - uses: actions/download-artifact@v8
        with:
          name: bin
          path: code

      - name: "Test built artifacts against stable"
        run: make test test_website
