on:
  pull_request:
    paths: [code/**, .github/workflows/Build.yaml]
  workflow_dispatch:
name: Build
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
defaults:
  run:
    shell: bash
    working-directory: code
jobs:
  build:
    name: "Build"
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/djarabek/drasil_fedora:latest
    steps:
      # https://github.com/commercialhaskell/stack/issues/2187#issuecomment-1013718541
      - name: Permissions bug workaround
        run: "chown -R $(id -un):$(id -gn) ~"
        working-directory: .

      - uses: actions/checkout@v6

      - name: "Cache dependencies"
        uses: actions/cache@v5
        with:
          path: |
            ~/.stack
          key: ${{ runner.os }}-store-v2-${{ hashFiles('code/stack.yaml') }}

      - run: locale

      - name: "Install dependencies"
        run: make stackArgs="--no-terminal" deps

      - name: "Build"
        run: make code stackArgs="--no-terminal" GHCFLAGS="-Werror -Wwarn=deprecations"

      - name: "Install"
        run: stack install --local-bin-path=bin
      
      - uses: actions/upload-artifact@v7
        with:
          name: bin
          path: code/bin
  
  gen:
    name: Generate
    needs: build
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/djarabek/drasil_fedora:latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/download-artifact@v8
        with:
          name: bin
          path: code/bin

      - name: "Set permssions"
        run: "chmod +x bin/*"

      - name: "Test built artifacts against stable"
        run: make test test_website

      - name: "Upload logs"
        if: ${{ failure() }}
        uses: actions/upload-artifact@v7
        with:
          name: logs
          path: code/logs

      - name: "Upload generated artifacts"
        uses: actions/upload-artifact@v7
        with:
          name: generated
          path: code/build

  haddock:
    name: Haddock
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/djarabek/drasil_fedora:latest
    steps:
      # https://github.com/commercialhaskell/stack/issues/2187#issuecomment-1013718541
      - name: Permissions bug workaround
        run: "chown -R $(id -un):$(id -gn) ~"
        working-directory: .

      - uses: actions/checkout@v6

      - name: "Restore cache"
        uses: actions/cache/restore@v5
        with:
          path: |
            ~/.stack
          key: ${{ runner.os }}-store-v2-${{ hashFiles('code/stack.yaml') }}

      - name: "Generate Haddock docs (as test)"
        run: make docs

  latex:
    name: LaTeX
    needs: gen
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/djarabek/drasil_fedora:latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/download-artifact@v8
        with:
          name: generated
          path: code/build

      - name: "Compile generated TeX artifacts"
        run: make -j tex SUMMARIZE_TEX=yes

  mdbook:
    name: mdBook
    needs: gen
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/djarabek/drasil_fedora:latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/download-artifact@v8
        with:
          name: generated
          path: code/build

      - name: "Build mdBook Examples"
        run: make mdbook_build
